server:
  port: 8000
application:
  name: book-store
spring:
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/book_db
    hikari:
    connection-timeout: 2000
    maximum-pool-size: 5